Copy Vs View

In [19]:
import numpy as np
var = np.array([1,2,3,5,6,7,4,4])
co = var.copy()
var[2] = 23 #Data add after copy data

print()
print("var: ",var)
print("copy: ",co)


var:  [ 1  2 23  5  6  7  4  4]
copy:  [1 2 3 5 6 7 4 4]


In [20]:
x = np.array([9,8,7,6,5,4,5,6,7,3,3,2,1])

vi = x.view()

x[2] = 23
print("x: ",x)
print("view: ",vi)

x:  [ 9  8 23  6  5  4  5  6  7  3  3  2  1]
view:  [ 9  8 23  6  5  4  5  6  7  3  3  2  1]


Join Array

In [21]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([12,45,56,65])

arr = np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5 12 45 56 65]


In [23]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([12,45,56,65])

arr_ = np.concatenate((arr_1,arr_2), axis=0)

print(arr_)

[ 1  2  3  4  5 12 45 56 65]


In [24]:
arr_3 = np.array([[1,2,3,4,5],[6,7,8,9,2]])
arr_4 = np.array([[11,21,13,41,15],[61,17,81,19,21]])

arr__ = np.concatenate((arr_3, arr_4), axis =0)
print(arr__)

[[ 1  2  3  4  5]
 [ 6  7  8  9  2]
 [11 21 13 41 15]
 [61 17 81 19 21]]


In [31]:
arr_5 = np.array([[11,21,31,41,51],[61,71,81,91,21]])
arr_6 = np.array([[11,21,13,41,15],[61,17,81,19,21]])

arr___ =np.stack((arr_5,arr_6), axis=0)
print(arr___)
print(arr___.ndim)


[[11 21 31 41 51]
 [61 71 81 91 21]
 [11 21 13 41 15]
 [61 17 81 19 21]]
2


In [40]:
ar_7 = np.array([[11,21,31,41,51],[61,71,81,91,21]])
ar_8 = np.array([[11,21,13,41,15],[61,17,81,19,21]])

ar1__ =np.vstack((arr_7,arr_8)) #Its work Along Column
print(ar1__)
print(ar1__.ndim)

ar2__ =np.hstack((arr_7,arr_8)) #Its work Along row
print(ar2__)
print(ar2__.ndim)

ar3__ =np.dstack((arr_7,arr_8)) #Its work Along height
print(ar3__)
print(ar3__.ndim)

[[11 21 31 41 51]
 [61 71 81 91 21]
 [11 21 13 41 15]
 [61 17 81 19 21]]
2
[[11 21 31 41 51 11 21 13 41 15]
 [61 71 81 91 21 61 17 81 19 21]]
2
[[[11 11]
  [21 21]
  [31 13]
  [41 41]
  [51 15]]

 [[61 61]
  [71 17]
  [81 81]
  [91 19]
  [21 21]]]
3
