Split Array

In [2]:
import numpy as np

In [3]:
var = np.array([1,2,3,4,5,6,7,8])

print(var)

ar = np.array_split(var,3)

print()
print(ar)

[1 2 3 4 5 6 7 8]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [16]:
var1 = np.array([[1,2,3,4,5,34],[12,45,56,65,6,7],[1,2,3,4,5,6]])

print(var1)

ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis=1)

print(ar1)
print(type(ar1))
print()
print(ar2)
print(type(ar2))

[[ 1  2  3  4  5 34]
 [12 45 56 65  6  7]
 [ 1  2  3  4  5  6]]
[array([[ 1,  2,  3,  4,  5, 34]]), array([[12, 45, 56, 65,  6,  7]]), array([[1, 2, 3, 4, 5, 6]])]
<class 'list'>

[array([[ 1,  2],
       [12, 45],
       [ 1,  2]]), array([[ 3,  4],
       [56, 65],
       [ 3,  4]]), array([[ 5, 34],
       [ 6,  7],
       [ 5,  6]])]
<class 'list'>


Search in Array

In [19]:
v1 = np.array([1,2,3,4,5,2,4,5,6,7,8,2,3,4,1,5,6,7,2,3,8,9])

x = np.where( v1 == 2)
print(x)

(array([ 1,  5, 11, 18], dtype=int64),)


In [24]:
v2 = np.array([1,2,3,4,6,7])

x1 = np.searchsorted( v2, 5)
print(x1)

4


In [25]:
v2 = np.array([1,2,3,4,5,2,4,5,6,7,8,2,3,4,1,5,6,7,2,3,8,9])

x2 = np.sort(v2)
print(x2)

[1 1 2 2 2 2 3 3 3 4 4 4 5 5 5 6 6 7 7 8 8 9]


Filter Array

In [30]:
v3 = np.array(["a", "b","c","d"])
f = [True,False,True,False]
x3 = v3[f]
print(x3)
print(type(x3))


['a' 'c']
<class 'numpy.ndarray'>
