In [6]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
y = [1, 2, 3, 4, 5]
print(y)
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


In [8]:
y = np.array([1, 2, 3, 4, 5])
print(y)
print(type(y))
type(y)

[1 2 3 4 5]
<class 'numpy.ndarray'>


numpy.ndarray

In [11]:
l = []
for i in range(1, 5):
    int_1 = int(input("enter:"))
    l.append(int_1)
print(np.array(l))
print(y.ndim)

enter: 1
enter: 2
enter: 4
enter: 6


[1 2 4 6]
1


In [12]:
ar2 = np.array([[1,2,3,4],[6,7,8,9],[12,123,456,67]])
print(ar2)
print(ar2.ndim)

[[  1   2   3   4]
 [  6   7   8   9]
 [ 12 123 456  67]]
2


In [13]:
ar3 = np.array([[[1,2,3,4],[23,65,34,56],[12,45,76,453]]])
print(ar3)
print(ar3.ndim)

[[[  1   2   3   4]
  [ 23  65  34  56]
  [ 12  45  76 453]]]
3


In [14]:
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [21]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print(ar_zero.ndim)
print()
print(ar_zero1)
print(ar_zero1.ndim)


[0. 0. 0. 0.]
1

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


In [22]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


Previous Memory ke hisab se empty array print hota hai

In [24]:
ar_empty = np.empty(4)
print(ar_empty)

[1. 1. 1. 1.]


dghg


In [25]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [27]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
ar_dia = np.eye(3, 5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [30]:
ar_lin = np.linspace(0, 20, num=6)
print(ar_lin)

[ 0.  4.  8. 12. 16. 20.]


In [34]:
arr_random = np.random.rand(3,6)
print(arr_random)

[[0.64663215 0.58977655 0.07566687 0.71836794 0.38814986 0.17668731]
 [0.31429995 0.00189474 0.03207072 0.39085805 0.41191608 0.3371985 ]
 [0.13243139 0.37922694 0.62541402 0.19729935 0.12581149 0.77882523]]


In [35]:
arr_random = np.random.randn(3,6)
print(arr_random)

[[-4.62518842e-01  2.00810465e-01  5.64292535e-02  3.82401407e-01
   2.46866079e-01  1.19526690e+00]
 [ 6.07865311e-02  1.46668437e-01 -9.29508444e-01 -7.04193325e-01
  -4.74728997e-01  1.02317514e+00]
 [ 7.97267631e-02 -1.44634668e+00 -8.04103292e-01  1.16166368e-03
  -1.41224841e+00 -6.09890791e-01]]


In [37]:
arr_random = np.random.ranf(6)
print(arr_random)

[0.30787063 0.06600593 0.55430306 0.58278061 0.22265096 0.72971789]


In [39]:
arr_random = np.random.randint(3,20,10)
print(arr_random)

[ 5  5 16  8 10 12  3 14  7  8]
