In [1]:
import numpy as np

In [3]:
x = np.array([[1,2,3,4],[2,3,5,6]])

print(x)
print()
print(x[0,1:3])
print(x[1,1:])

[[1 2 3 4]
 [2 3 5 6]]

[2 3]
[3 5 6]


In [9]:

x1 = np.array([[[1,2,3],[1,2,5]],[[2,3,4],[6,7,9]]])

print(x1)
print()
print(x1.ndim)
print(x1[1,1,1:])

[[[1 2 3]
  [1 2 5]]

 [[2 3 4]
  [6 7 9]]]

3
[7 9]


Iteration

In [10]:
var = np.array([9,8,7,6,5,4,3,2,1])
print(var)
print()
for i in var:
    print(i)

[9 8 7 6 5 4 3 2 1]

9
8
7
6
5
4
3
2
1


In [15]:
var1 = np.array([[1,2,3,4,5],[6,7,8,9,2]])
print(var1)
print()
for i in var1:
    print(i)
print()
for j in var1:
    for k in j:
        print(k) # Iterated Data

[[1 2 3 4 5]
 [6 7 8 9 2]]

[1 2 3 4 5]
[6 7 8 9 2]

1
2
3
4
5
6
7
8
9
2


In [20]:
var2 = np.array([[[1,2,3],[1,2,5]],[[2,3,4],[6,7,9]]])

print(var2)
print()
for i in var2:
    for j in i:
        for k in j:
            print(k) #Iterated data 

[[[1 2 3]
  [1 2 5]]

 [[2 3 4]
  [6 7 9]]]

1
2
3
1
2
5
2
3
4
6
7
9


In [22]:
var3 = np.array([[[1,2,3],[1,2,5]],[[2,3,4],[6,7,9]]])
print(var3)
print()

for i in np.nditer(var3):
    print(i)
    

[[[1 2 3]
  [1 2 5]]

 [[2 3 4]
  [6 7 9]]]

1
2
3
1
2
5
2
3
4
6
7
9


In [24]:
var4 = np.array([[[1,2,3],[1,2,5]],[[2,3,4],[6,7,9]]])
print(var4)
print()

for i in np.nditer(var4, flags=['buffered'],op_dtypes=["S"]): # Data Buffered, Data stored in buffered 
    print(i)
    

[[[1 2 3]
  [1 2 5]]

 [[2 3 4]
  [6 7 9]]]

b'1'
b'2'
b'3'
b'1'
b'2'
b'5'
b'2'
b'3'
b'4'
b'6'
b'7'
b'9'


In [25]:
var5 = np.array([[[1,2,3],[1,2,5]],[[2,3,4],[6,7,9]]])
print(var5)
print()

for i in np.ndenumerate(var5):
    print(i)
    

[[[1 2 3]
  [1 2 5]]

 [[2 3 4]
  [6 7 9]]]

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 1, 0), 1)
((0, 1, 1), 2)
((0, 1, 2), 5)
((1, 0, 0), 2)
((1, 0, 1), 3)
((1, 0, 2), 4)
((1, 1, 0), 6)
((1, 1, 1), 7)
((1, 1, 2), 9)


In [30]:
var6 = np.array([[1,2,3,4],[5,6,7,8]])
print(var6)
for i,d in np.ndenumerate(var6):
    print(i,d)

[[1 2 3 4]
 [5 6 7 8]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
