Shuffle, Unique, Resize, Flatten, Ravel Functions 

In [19]:
import numpy as np
v1 = np.array([1,2,3,4,5])

np.random.shuffle(v1)
print(v1)

[1 5 4 3 2]


In [21]:
v2 = np.array([1,2,3,4,5,3,4,2,3,4,5,6,6,7,8,2,3,1,2,3,4,5,6])
x2 =np.unique(v2)
print(x2)


[1 2 3 4 5 6 7 8]


In [24]:
v3 = np.array([1,2,3,4,5,3,4,2,3,4,5,6,6,7,8,2,3,1,2,3,4,5,6])

x3 = np.unique(v3,return_index=True,return_counts=True)

print(x3)



(array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 0,  1,  2,  3,  4, 11, 13, 14], dtype=int64), array([2, 4, 5, 4, 3, 3, 1, 1], dtype=int64))


In [27]:
v4 = np.array([1,2,3,4,5,3,4,2,3,4,5,6,6,7,8,2,3,1,2,3,4,5,6,5])

x4 = np.resize(v4,(4,6))
print(x4)

[[1 2 3 4 5 3]
 [4 2 3 4 5 6]
 [6 7 8 2 3 1]
 [2 3 4 5 6 5]]


In [30]:
v5 = np.array([1,2,3,4,5])

x5 = np.resize(v5,(3,2))
print(x5)
print()

print("Flatten: ",x5.flatten(order="F"))
print("Ravel: ",np.ravel(x5,order="F"))

[[1 2]
 [3 4]
 [5 1]]

Flatten:  [1 3 5 2 4 1]
Ravel:  [1 3 5 2 4 1]


Insert And Delete In Array

In [34]:
v6 = np.array([1,2,3,4,5])
print(v6)
# x6 = np.insert(v6, 4, 3400)
x6 = np.insert(v6, (2,4), 34)


print(x6)

[1 2 3 4 5]
[ 1  2 34  3  4 34  5]


In [35]:
v7 = np.array([1,2,3,4,5])
print(v7)

x7 = np.delete(v7, 2)
print(x7)


[1 2 3 4 5]
[1 2 4 5]


Matrix

In [40]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()

print(np.transpose(var))
print()

print(var.T)
print()

print(np.swapaxes(var,0,1))


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [43]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))
print(np.linalg.inv(var2))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [50]:
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()

print(np.linalg.matrix_power(var3,2))
print()

print(np.linalg.matrix_power(var3,0))
print()

print(np.linalg.matrix_power(var3,-2))
print()

print(np.linalg.det(var3))


[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]

-2.0000000000000004
