In [5]:
import numpy as np
x = np.array([1,2,3,4])
print("Data Type: ", x.dtype)
print(x)

Data Type:  int32
[1 2 3 4]


In [20]:
x1 = np.array([1.0,2.0,4.0,4.7])
print("Data Type: ", x1.dtype)
print(x1)

Data Type:  float64
[1.  2.  4.  4.7]


In [21]:
x2 = np.array([1,2,3,4], dtype= "f")
print("Data Type: ", x2.dtype)
print(x2)

Data Type:  float32
[1. 2. 3. 4.]


In [25]:
x3 = np.array([1,2,3,4])
new = np.float32(x2)
print("Data Type: ", x3.dtype)
print("Data Type: ", new.dtype)
print(x3)
print(new)


Data Type:  int32
Data Type:  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [26]:
x4 = np.array([1,2,3,4])
new_1 = x4.astype(float)
print(x4)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


In [29]:
x5 = np.array([[1,2,3,4], [2,3,4,5]])
print(x5)
print()
print(x5.shape)

[[1 2 3 4]
 [2 3 4 5]]

(2, 4)


In [38]:
var = np.array([[[1,2,3,4], [4,5,6,7],[8,9,10,11]]])
print(var)
print()
print(var.ndim)
y = var.reshape(2,3,2)
print(y)
print(var.ndim)


[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 8  9 10 11]]]

3
[[[ 1  2]
  [ 3  4]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
3


In [45]:
var = np.array([[[1,2,3,4], [4,5,6,7],[8,9,10,11]]])
print(var)
print()
print(var.ndim)
y = var.reshape(2,3,2)
print(y)
print(var.ndim)

print()
one = y.reshape(-1)
print(one)
print(one.ndim)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 8  9 10 11]]]

3
[[[ 1  2]
  [ 3  4]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
3

[ 1  2  3  4  4  5  6  7  8  9 10 11]
1


In [49]:
a = np.array([3,5,6,7])
b = np.array([1,2,3,4])
print(np.add(a,b))
print()
print(np.subtract(a,b))
print()
print(np.add(a,b))
print()
print(np.multiply(a,b))
print()
print(np.divide(a,b))
print()
print(np.mod(a,b))
print()
print(np.power(a,b))
print()
print(np.reciprocal(a,b))

[ 4  7  9 11]

[2 3 3 3]

[ 4  7  9 11]

[ 3 10 18 28]

[3.   2.5  2.   1.75]

[0 1 0 3]

[   3   25  216 2401]

[0 0 0 0]


In [50]:
ar_fun = np.array([3,5,6,7])

print(np.min(ar_fun))
print()
print(np.max(ar_fun))
print()
print(np.argmin(ar_fun))
print()
print(np.sqrt(ar_fun))
print()
print(np.sin(ar_fun))
print()
print(np.cos(ar_fun))
print()
print(np.cumsum(ar_fun))
print()


3

7

0

[1.73205081 2.23606798 2.44948974 2.64575131]

[ 0.14112001 -0.95892427 -0.2794155   0.6569866 ]

[-0.9899925   0.28366219  0.96017029  0.75390225]

[ 3  8 14 21]



In [5]:
import numpy as np
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3], [1,2,3]])
print(y.shape)

print()
print(x)
print(y)
print()
print(x+y)

(2, 1)
(2, 3)

[[1]
 [2]]
[[1 2 3]
 [1 2 3]]

[[2 3 4]
 [3 4 5]]


Indexing Numpy Arrays


In [8]:
x = np.array([1,2,3,4,5,6,7,8,90])
print(x[2])
print(x[-7])

3
3


In [15]:
y = np.array([[9,8,7],[4,5,6]])
print(y)
print(y.ndim)
print()

print(y[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [18]:
 z = np.array([[[1,2,3,4],[3,4,5,6],[7,8,9,10]]])
print(z[0, 2,3])

10


Slicing

In [22]:
 s = np.array([1,2,3,4,5,6,7,8,9])

print(s)
print()

print(s[2:7])
print(s[2:])
print(s[:7])

[1 2 3 4 5 6 7 8 9]

[3 4 5 6 7]
[3 4 5 6 7 8 9]
[1 2 3 4 5 6 7]
